name: CI Pipeline

on:
    push:
        branches:
            - main


jobs:
    linting-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Python3.12.3
              uses: actions/setup-python@v4
              with:
                python-version: '3.12.3'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run pre-commit hooks
              run: pre-commit run --all-files

    testing:
        runs-on: ubuntu-latest
        needs: linting-check

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Python3.12.3
              uses: actions/setup-python@v4
              with:
                python-version: '3.12.3'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run Tests
              run: pytest -s
              env:
                API_KEY: ${{secrets.API_KEY}}


    docker-check:
        runs-on: ubuntu-latest
        needs: testing

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build Docker image
              run: docker build -t currency-converter:latest .
